// <auto-generated />
namespace Cash_Inspection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fss1s : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fss1s));
        
        string IMigrationMetadata.Id
        {
            get { return "201512220347340_fss1s"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
